# EM algorithm for Multivariate Gaussian Mixture Model

### Data import
```{R}
iris = read.csv("D:/Projects/EM-algorithm/data/Iris.csv", header = TRUE, sep = ",") 

iris2 = iris[,1:4]

print(iris2)
```

### Algorithm implementation
```{R}
#------------------------ Expectation-Maximization Algorithm -----------------------
gaussmixEM = function(params, X, clusters = 2, tol=.00001, maxits=100, showits=T){
  # Arguments: 
  # params: list of values for mu, var, and probs
  # X: data matrix
  # clusters: number of clusters
  # tol: tolerance for convergence
  # maxits: maximum number of iterations
  # showits: print iterations or not

  require(mvtnorm)
  # Starting points
  N = nrow(X)
  mu = params$mu
  var = params$var
  probs = params$probs
  
  # initializations
  responsibility = matrix(0, ncol=clusters, nrow=N)
  logLikelihood = 0
  iteration = 0
  converged = FALSE
  
  if (showits)
    cat(paste("Iterations of EM:", "\n"))
  
  while (iteration < maxits) { 
    if(converged) break
    probsOld = probs
    logLikelihoodOld = logLikelihood
    responsibilityOld = responsibility
    
#-------------------------------- Expectation-Step ---------------------------------
    # Compute responsibilities
    for (k in 1:clusters){
      responsibility[,k] = probs[k] * dmvnorm(X, mu[k,], sigma = var[[k]], log=F)
    }
    responsibility = responsibility/rowSums(responsibility)
    
#-------------------------------- Maximization-Step --------------------------------
    rk = colSums(responsibility)
    probs = rk/N
    for (k in 1:clusters){
      varMatrix = matrix(0, ncol=ncol(X), nrow=ncol(X))
      for (i in 1:N){
        varMatrix = varMatrix + responsibility[i,k] * X[i,]%*%t(X[i,])
      }
      mu[k,] = (t(X) %*% responsibility[,k]) / rk[k]
      var[[k]] =  varMatrix/rk[k] - mu[k,]%*%t(mu[k,])
      logLikelihood[k] = -.5 * sum( responsibility[,k] * dmvnorm(X, mu[k,], sigma = var[[k]], log=T) )
    }
    logLikelihood = sum(logLikelihood)
    
    ### compare old to current for convergence
    paramsOld =  c(logLikelihoodOld, probsOld)
    paramsCurrent = c(logLikelihood, probs)
    iteration = iteration + 1
    if (showits & iteration == 1 | iteration%%5 == 0)
      cat(paste(format(iteration), "...", "\n", sep = ""))
    
    if(min(abs(paramsOld - paramsCurrent)) < tol) {
            converged = TRUE
    }
  }
  
  cluster = which(round(responsibility)==1, arr.ind=T)
  cluster = cluster[order(cluster[,1]), 2]
  out = list(probs=probs, mu=mu, var=var, resp=responsibility, cluster=cluster, logLikelihood=logLikelihood)
} 
```

## Iris dataset

##### Run EM algorithm - general starting values (on the whole dataset and duplicated for the number of wanted clusters)
```{R}
library(plyr)

# Create starting values
Mu = daply(iris2, NULL, function(x) colMeans(x)) + runif(4, 0, 0.5)
Cov = dlply(iris2, NULL, function(x) var(x) + diag(runif(4, 0, 0.5)))
initProbs = c(.1, .2, .7)

column.names <- c("SepalLengthCm", "SepalWidthCm", "PetalLengthCm", "PetalWidthCm")
row.names <- c("Cluster 1", "Cluster 2", "Cluster 3")

# Create list of starting values
initMu = array(c(Mu[1] + 0.1, Mu[1] + 0.2, Mu[1] + 0.3, Mu[2] + 0.1, Mu[2] + 0.2, Mu[2] + 0.3, Mu[3] + 0.1, Mu[3] + 0.2, Mu[3] + 0.3, Mu[4] + 0.1, Mu[4] + 0.2, Mu[4] + 0.4) , dim = c(3, 4),dimnames = list(row.names,column.names))
covInit <- list('Cluster 1' = Cov[[1]], 'Cluster 2' = Cov[[1]], 'Cluster 3' = Cov[[1]])

initParams = list(mu=initMu, var=covInit, probs=initProbs)  

print(initParams)

# Run and examine
test = gaussmixEM(params=initParams, X=as.matrix(iris2), clusters = 3, tol=1e-8, maxits=1500, showits=T)
table(test$cluster, iris$Species)

#    Iris-setosa Iris-versicolor Iris-virginica
#  1          50               0              0
#  2           0              36             16
#  3           0              14             34
```

##### Results visualization
```{R}
library(ggplot2)

png('D:/Projects/EM-algorithm/plots/em-mgmm-plot-iris-example-general.png', width=1080, height=1080)
options(repr.plot.width = 5, repr.plot.height =5)
# Scatter plot of clusters
ggplot(data = iris, aes(x = iris2$SepalLengthCm, y = iris2$SepalWidthCm, color = as.factor(test$cluster))) +
  geom_point(size = 3) +
  geom_point(data = as.data.frame(test$mu), aes(x = test$mu[,1], y = test$mu[,2]), color = "black", size = 4) +
  labs(title = "Scatter Plot of Clusters and Centroids", x = "Sepal Length", y = "Sepal Width") +
  theme(text = element_text(size = 15), aspect.ratio = 1)

dev.off()
```

##### Run EM algorithm - specified starting values (used the speciies to have the starting values for each cluster)
```{R}
library(plyr)

# Create starting values
initMu = daply(iris, 'Species', function(x) colMeans(x[,1:4])) + runif(4, 0, .5)
initCov = dlply(iris, 'Species', function(x) var(x[,1:4]) + diag(runif(4, 0, .5)))
initProbs = c(.1, .2, .7)

initParams = list(mu=initMu, var=initCov, probs=initProbs)  

# Run and examine
test = gaussmixEM(params=initParams, X=as.matrix(iris2), clusters = 3, tol=1e-8, maxits=1500, showits=T)
table(test$cluster, iris$Species)

#    Iris-setosa Iris-versicolor Iris-virginica
#  1          50               0              0
#  2           0              48              1
#  3           0               2             49
```

##### Results visualization
```{R}
library(ggplot2)

png('D:/Projects/EM-algorithm/plots/em-mgmm-plot-iris-example-specific.png', width=1080, height=1080)
options(repr.plot.width = 5, repr.plot.height =5)
# Scatter plot of clusters
ggplot(data = iris, aes(x = iris2$SepalLengthCm, y = iris2$SepalWidthCm, color = as.factor(test$cluster))) +
  geom_point(size = 3) +
  geom_point(data = as.data.frame(test$mu), aes(x = test$mu[,1], y = test$mu[,2]), color = "black", size = 4) +
  labs(title = "Scatter Plot of Clusters and Centroids", x = "Sepal Length", y = "Sepal Width") +
  theme(text = element_text(size = 15), aspect.ratio = 1)
dev.off()
```

## Mall Customers dataset

##### Data import
```{R}
MallCustomers = read.csv("D:/Projects/EM-algorithm/data/Mall_Customers_Clean.csv", header = TRUE, sep = ",")

print(MallCustomers)
```

##### Column selection
```{R}
# Select columns for analysis
X <- MallCustomers[,c(2,4)]
```

##### Run EM algorithm - general starting values (on the whole dataset and duplicated for the number of wanted clusters) - for columns 'Age' and 'Spending Score (1-100)'
```{R}
library(plyr)
# Create starting values
Mu = daply(X, NULL, function(x) colMeans(x)) + runif(2, 0, .5)
Cov = dlply(X, NULL, function(x) var(x) + diag(runif(2, 0, .5)))
initProbs = c(.1, .3, .6, 0.9)

column.names <- c("Age", "Spending Score (1-100)")
row.names <- c("Cluster 1", "Cluster 2", "Cluster 3", "Cluster 4")

initMu = array(c(Mu[1] + 0.1, Mu[1] + 0.2, Mu[1] + 0.3, Mu[1] + 0.4, Mu[2] + 0.1, Mu[2] + 0.2, Mu[2] + 0.3, Mu[2] + 0.4), dim = c(4,2),dimnames = list(row.names,column.names))
initCov <- list('Cluster 1' = Cov[[1]], 'Cluster 2' = Cov[[1]], 'Cluster 3' = Cov[[1]], 'Cluster 4' = Cov[[1]])

initParams <- list(mu = initMu, var = initCov, probs = initProbs)

print(initParams)
# Run and examine
results = gaussmixEM(params=initParams, X=as.matrix(X), clusters = 4, tol=1e-8, maxits=1500, showits=T)

```

##### Results visualization
```{R}
library(ggplot2)

png('D:/Projects/EM-algorithm/plots/em-mgmm-plot-mall-customers-example-general-2cols.png', width=1080, height=1080)
options(repr.plot.width = 5, repr.plot.height =5)
# Scatter plot of clusters
ggplot(data = X, aes(x = X[,1], y = X[,2], color = as.factor(c(results$cluster, 1)))) +
  geom_point(size = 3) +
  geom_point(data = as.data.frame(results$mu), aes(x = results$mu[,1], y = results$mu[,2]), color = "black", size = 4) +
  labs(title = "Scatter Plot of Clusters and Centroids", x = "Age", y = "Spending Score (1-100)") +
  theme(text = element_text(size = 15), aspect.ratio = 1)

dev.off()
```

##### Run EM algorithm - general starting values (on the whole dataset and duplicated for the number of wanted clusters) - on all columns
```{R}
library(plyr)
# Create starting values
Mu = daply(MallCustomers, NULL, function(x) colMeans(x)) + runif(4, 0, 0.5)
Cov = dlply(MallCustomers, NULL, function(x) var(x) + diag(runif(4, 0, 0.5)))

column.names <- c("Gender", "Age", "Annual Income (k$)", "Spending Score (1-100)")
row.names <- c("Cluster 1", "Cluster 2", "Cluster 3", "Cluster 4")

initMu = array(c(Mu[1] + 0.1, Mu[1] + 0.2, Mu[1] + 0.3, Mu[1] + 0.4, Mu[2] + 0.1, Mu[2] + 0.2, Mu[2] + 0.3, Mu[2] + 0.4, Mu[3] + 0.1, Mu[3] + 0.2, Mu[3] + 0.3, Mu[3] + 0.4, Mu[4] + 0.1, Mu[4] + 0.2, Mu[4] + 0.3, Mu[4] + 0.4) , dim = c(4, 4),dimnames = list(row.names,column.names))
initCov <- list('Cluster 1' = Cov[[1]], 'Cluster 2' = Cov[[1]], 'Cluster 3' = Cov[[1]], 'Cluster 4' = Cov[[1]])
initProbs = c(.1, .35, .65, .9)

initParams <- list(mu = initMu, var = initCov, probs = initProbs)

print(initParams)
# Run and examine

# BUG
# Error in if (min(abs(paramsOld - paramsCurrent)) < tol) { : 
# missing value where TRUE/FALSE needed


results = gaussmixEM(params=initParams, X=as.matrix(MallCustomers), clusters = 4, tol=1e-8, maxits=1500, showits=T)
print(results)
```

```{R}
print(results)
library(ggplot2)

#png('D:/Projects/EM-algorithm/plots/em-mgmm-plot-iris-example.png', width=1080, height=1080)
options(repr.plot.width = 5, repr.plot.height =5)
# Scatter plot of clusters
ggplot(data = MallCustomers, aes(x = MallCustomers[,1], y = MallCustomers[,2], color = as.factor(c(results$cluster, 1)))) +
  geom_point(size = 3) +
  geom_point(data = as.data.frame(results$mu), aes(x = results$mu[,1], y = results$mu[,2]), color = "black", size = 4) +
  labs(title = "Scatter Plot of Clusters and Centroids", x = "Age", y = "Spending Score (1-100)") +
  theme(text = element_text(size = 15), aspect.ratio = 1)

#dev.off()
```
